export const tracingIgnoreRoutes = [
  '/altair',
  '/altair/styles.css',
  '/altair/assets/img/logo_350.svg',
  '/altair/runtime-es2018.js',
  '/altair/polyfills-es2018.js',
  '/altair/main-es2018.js',
  '/favicon.ico',
  '/altair/favicon.ico',
  '/altair/assets/i18n/default.json',
  '/altair/assets/i18n/en-US.json',
  '/altair/14-es2018.js',
  '/altair/assets/img/logo.svg',
  '/altair/0-es2018.worker.js',
  '/altair/jetbrains-mono-latin-400-normal.woff2',
  '/altair/0-es2018.worker.js',
  '/altair/13-es2018.js',
]
